services:
  potgres_db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  file_db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - files:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  file-storager-service:
    build:
      context: ./file-storager
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - potgres_db
      - file_db

  file-analyzer-service:
    build:
      context: ./file-analyzer
      dockerfile: Dockerfile
    ports:
      - 8083:8083

  core-service:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - file-analyzer-service
      - file-storager-service

  api-gateway:
    build:
      context: ./api-router
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - core-service

volumes:
  pg:
  files:
