basePath: /
host: file-storager-service:8083
info:
  contact: {}
  description: Service for managing stored files in DB.
  title: File Storage Manager
  version: "1.0"
paths:
  /files/{id}:
    get:
      description: Download file from DB.
      parameters:
      - description: Id of file
        in: path
        name: id
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: formData
        "401":
          description: Unauthorized
          schema:
            type: body
        "500":
          description: Internal Server Error
          schema:
            type: body
  /files/analysis/{id}:
    post:
      consumes:
      - application/json
      description: Save analysis result to DB.
      parameters:
      - description: Id of file
        in: path
        name: id
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: body
        "500":
          description: Internal Server Error
          schema:
            type: body
  /files/check/{id}:
    get:
      description: Check if file exists in DB.
      parameters:
      - description: Id of file
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: body
        "401":
          description: Unauthorized
          schema:
            type: body
        "500":
          description: Internal Server Error
          schema:
            type: body
  /files/upload:
    post:
      consumes:
      - text/plain
      description: Upload file to DB.
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      - description: Id of file
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: body
        "500":
          description: Internal Server Error
          schema:
            type: body
swagger: "2.0"
