// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/files/analyze": {
            "post": {
                "description": "Analyze file.",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "Text to analyze.",
                        "name": "text",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.Analysis"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/files/wordcloud": {
            "post": {
                "description": "Get word cloud.",
                "produces": [
                    "image/png"
                ],
                "parameters": [
                    {
                        "description": "Text to analyze.",
                        "name": "text",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.Analysis": {
            "type": "object",
            "properties": {
                "average_length_of_words": {
                    "type": "number"
                },
                "average_sentences_per_paragraph": {
                    "type": "number"
                },
                "average_words_per_sentence": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "paragraphs_amount": {
                    "type": "integer"
                },
                "sentences_amount": {
                    "type": "integer"
                },
                "symbols_amount": {
                    "type": "integer"
                },
                "words_amount": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "File Analyzer",
	Description:      "Service for analyzing files.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
